# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableView+JSONParsing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TableView+JSONParsing
  pod 'SwiftyJSON', "=4.0.0-alpha.1"
  pod 'SDWebImage'

  target 'TableView+JSONParsingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TableView+JSONParsingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
