# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSONfromAPI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JSONfromAPI
   pod 'Alamofire'
   pod 'SwiftyJSON'
   pod 'SDWebImage'

  target 'JSONfromAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JSONfromAPIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
